### ISSUE TITLE
考虑自动化管理版本号，Major.Minor.Patch

### ISSUE THREAD

**Issue by ylongwang2782** [ylongwang2782/wht#116]

**Comment by ylongwang2782** [comment]
可以使用Git标签来集中管理

你已经有一套构建变体（`BUILD_VARIANT`）控制逻辑了，下面我将教你如何**集成 Git 标签**来自动化版本号控制，同时**兼容你已有的 CMake 架构**。

---

## ✅ 目标

让你的 `CMakeLists.txt` 自动从 Git 标签（如 `v3.1.2`）中读取 `VERSION`，**替代硬编码的 `project(... VERSION X.Y.Z)`**。

---

## 🛠 修改后的 `CMakeLists.txt` 示例

请替换你原来的版本号设定部分为以下代码段：

```cmake
# 获取 Git 标签作为版本号
execute_process(
  COMMAND git describe --tags --abbrev=0
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_TAG
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

# 提取 MAJOR, MINOR, PATCH
string(REGEX MATCH "([0-9]+)\\.([0-9]+)\\.([0-9]+)" VERSION_MATCH ${GIT_TAG})
if(VERSION_MATCH)
  string(REGEX REPLACE "([0-9]+)\\.([0-9]+)\\.([0-9]+)" "\\1" PROJECT_VERSION_MAJOR ${VERSION_MATCH})
  string(REGEX REPLACE "([0-9]+)\\.([0-9]+)\\.([0-9]+)" "\\2" PROJECT_VERSION_MINOR ${VERSION_MATCH})
  string(REGEX REPLACE "([0-9]+)\\.([0-9]+)\\.([0-9]+)" "\\3" PROJECT_VERSION_PATCH ${VERSION_MATCH})
else()
  message(WARNING "Invalid git tag: ${GIT_TAG}, using default version 0.0.0")
  set(PROJECT_VERSION_MAJOR 0)
  set(PROJECT_VERSION_MINOR 0)
  set(PROJECT_VERSION_PATCH 0)
endif()

# 设置项目名称和版本号（保留你的 BUILD_VARIANT 结构）
if(BUILD_VARIANT STREQUAL "MASTER_DEBUG")
  project(MasterFirmware VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
elseif(BUILD_VARIANT STREQUAL "MASTER_RELEASE")
  project(MasterFirmwareRelease VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
elseif(BUILD_VARIANT STREQUAL "SLAVE_DEBUG")
  project(SlaveFirmware VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
elseif(BUILD_VARIANT STREQUAL "SLAVE_RELEASE")
  project(SlaveFirmwareRelease VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
elseif(BUILD_VARIANT STREQUAL "BOARDTEST")
  project(BoardTestFirmware VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
else()
  message(FATAL_ERROR "Unknown BUILD_VARIANT value: ${BUILD_VARIANT}")
endif()
```

---

## ✅ Git 标签格式说明

你应按照以下方式打 Git 标签：

```bash
git tag v3.2.5
```

它将被 `git describe --tags` 自动读取。

---

## 🧩 可选：生成 `version.h`

如果你想让代码中可以访问版本号，比如用于打印日志：

```cpp
Log.d("[BOOT] Board Test Firmware v%s, Built: %s %s", VERSION_STRING, __DATE__, __TIME__);
```

你可以生成一个 `version.h`：

```cmake
set(VERSION_HEADER_PATH "${CMAKE_BINARY_DIR}/version.h")
file(WRITE ${VERSION_HEADER_PATH}
"#pragma once\n"
"#define FW_VERSION_MAJOR ${PROJECT_VERSION_MAJOR}\n"
"#define FW_VERSION_MINOR ${PROJECT_VERSION_MINOR}\n"
"#define FW_VERSION_PATCH ${PROJECT_VERSION_PATCH}\n"
"#define VERSION_STRING \"v${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}\"\n"
)

include_directories(${CMAKE_BINARY_DIR})
```

---

## 🚀 提交自动打标签（进阶）

你还可以：

* 用 `git tag` + CI 脚本在 PR 合并时自动增加 patch；
* 或者手动运行：

```bash
# 假设当前为 v3.1.4，则自动计算新版本：
git tag v3.1.5
git push origin v3.1.5
```

---

需要我帮你写一个 GitHub Actions 脚本来实现自动 tag 吗？还是说你希望在本地 build 时就能自动增加 patch？我可以提供具体脚本。

**Comment by ylongwang2782** [comment]
另外在commit，pull request以及tag过程中应该严格遵守以下规则
这是一个非常实用的问题，关系到 **Git 分支管理规范（如 Git Flow）** 和 **版本发布时机** 的最佳实践。

---

## ✅ 正确顺序（推荐）

你在 **开发（修复 issue）过程中**，**不要立刻打 tag**。应该按照如下顺序进行：

---

### 🛠 工作流程

1. **从主干分支（如 `main` 或 `develop`）拉出新分支**

   ```bash
   git checkout -b fix/issue-123
   ```

2. **修复 bug / 开发 feature**

   * 正常开发，可能有多个 commit。

3. **本地测试通过后提交并 push 分支**

   ```bash
   git push origin fix/issue-123
   ```

4. **创建 Pull Request（PR）合并到主干**

   * PR 标题例如：`Fix: 修复 IO 串口初始化失败的问题 (issue #123)`
   * CI/CD 会对 PR 进行构建/测试

5. **PR 被审核并合并（merge）到 `main` 或 `release` 分支**

6. ✅ **此时打 Tag（版本号）**

   * 假设修复后是 `v3.1.2`

   ```bash
   git checkout main
   git pull
   git tag v3.1.2
   git push origin v3.1.2
   ```

---

## ❌ 不推荐：修复前就打 tag

在修复前就打 tag 有两个问题：

1. **代码还没完成，不知道最终版本号是什么**
2. **tag 的代码不是稳定状态，容易造成误导**

---

## 🧠 简单记忆法

> ✅ “**代码稳定后才发布版本**，版本要代表可以被发布、构建、上线的节点。”

---

## 🚀 如果你使用 GitHub Actions，还可以在合并 PR 时自动打 tag

如果你需要，我可以帮你写一段 GitHub Actions 脚本，让它在 PR 合并到 `main` 时自动读取上一个 tag、+1 patch，然后打 tag。

---

要不要我帮你配一个自动 tag 脚本？或者配一个完整的版本号从 tag 读取、自动更新 `version.h`、CI 自动打包上传 release 的工作流？

**Comment by ylongwang2782** [comment]
还可以通过github action来实现每次提交PR时，patch自动+1
好的，下面是一个完整的 GitHub Actions 工作流脚本，它会在 **Pull Request 合并到 `main` 分支时**：

1. 自动获取最近的 tag（如 `v3.0.4`）
2. 自动生成新的 patch tag（如 `v3.0.5`）
3. 自动打上这个新 tag 并推送到远程仓库

---

## ✅ GitHub Actions：自动递增 patch 版本并打 tag

请将以下内容保存为 `.github/workflows/autotag.yml`：

```yaml
name: Auto Tag Patch Version

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    name: Auto Increment Patch Version Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整历史以获取 tag 列表

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> "$GITHUB_OUTPUT"

      - name: Bump patch version
        id: bump_tag
        run: |
          tag=${{ steps.get_tag.outputs.tag }}
          version=${tag#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_tag="v$major.$minor.$patch"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> "$GITHUB_OUTPUT"

      - name: Create new tag
        run: |
          git tag ${{ steps.bump_tag.outputs.new_tag }}
          git push origin ${{ steps.bump_tag.outputs.new_tag }}
```

---

## ✅ 效果说明

* 如果上一次是 `v3.0.4`，合并 PR 到 `main` 时会自动创建 `v3.0.5`
* 不依赖本地脚本，无需手动执行
* 可扩展为：**根据 commit message 自动决定是 patch / minor / major（如 Semantic Versioning）**

---

## ✅ 可选扩展：自动生成 changelog

如需加 changelog 和 GitHub Release 发布，也可以加一行：

```yaml
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_tag.outputs.new_tag }}
```

---

是否需要将这个 tag 自动写入你的 CMake 或 C 头文件里？我可以帮你自动生成 `version.h` 或 `version.hpp`。

**Comment by ylongwang2782** [comment]
还可以根据commit自动决定是patch还是minor
很棒的问题，下面一一解答：

---

### ✅ **1. 这个文件是否需要存放在你的仓库中？**

**是的**，这个 GitHub Actions 工作流脚本需要存放在你的仓库中，具体路径如下：

```
.yarn/github/workflows/autotag.yml
```

即：

```
你的仓库根目录/
├── .github/
│   └── workflows/
│       └── autotag.yml  ← 把脚本放这里
```

只要这个文件在该路径下，GitHub 会自动执行你配置的触发条件（如合并到 `main` 时）。

---

### ✅ **2. 如何根据 Commit Message 自动决定是 Patch / Minor / Major？**

这是 Semantic Versioning 自动化的核心需求，你可以借助工具实现，比如：

* [`[conventional-commits](https://www.conventionalcommits.org/)`](https://www.conventionalcommits.org/)
* [`[semantic-release](https://github.com/semantic-release/semantic-release)`](https://github.com/semantic-release/semantic-release)

下面是 **推荐方案**：使用 `conventional-changelog/standard-version` + GitHub Actions 自动处理版本号。

---

## 🚀 示例：根据 commit message 自动决定版本类型

### ✅ 使用标准格式提交（Conventional Commits）

示例：

```bash
git commit -m "fix: 修复以太网初始化失败"
git commit -m "feat: 添加新硬件 watchdog 支持"
git commit -m "BREAKING CHANGE: 修改接口定义，不兼容旧版"
```

* `fix:` → 自动 bump **patch**
* `feat:` → 自动 bump **minor**
* `BREAKING CHANGE:` 或 `!` → bump **major**

---

### ✅ GitHub Actions 脚本（自动语义化版本号）

保存为 `.github/workflows/release.yml`：

```yaml
name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Versioning Auto Tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
```

### ✅ 配置文件：`release.config.js`

在项目根目录新建 `release.config.js`：

```js
module.exports = {
  branches: ['main'],
  plugins: [
    '@semantic-release/commit-analyzer', // 分析 commit 类型
    '@semantic-release/release-notes-generator', // 自动生成 changelog
    '@semantic-release/changelog',
    '@semantic-release/git', // 提交 changelog 和版本号变更
    '@semantic-release/github' // 发布 GitHub Release
  ],
  preset: 'conventionalcommits',
};
```

---

### ✅ 效果

* 自动识别提交类型 → 计算新版本号（如 `v3.2.5` → `v3.3.0`）
* 自动打 tag、生成 release、更新 changelog
* 无需手动改版本号或打 tag

---

如果你希望在 **CMake 或代码里引用版本号**，我也可以提供自动生成 `version.h` 或 `config.h` 的方式，把 Git 标签写入代码中。

是否要我一并加上这个功能？
